let Constants = {
    BASE_URL: '//localhost:9999/ele',
    DEFAULT_LNG: 'en',
    ENTER_BUSINESS: 'ENTER_BUSINESS',
    GOTO: 'GOTO',
    GO_BACK: 'GO_BACK',
    GO_FORWARD: 'GO_FORWARD',
    MERGE_DATA: 'MERGE_DATA',
    GET_HOME_BUSINESS: 'GET_HOME_BUSINESS',
    GET_SEARCH_BUSINESS: 'GET_SEARCH_BUSINESS',
    REPLACE_DATA: 'REPLACE_DATA'
};

export default Constants;
